name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit coverage

    - name: Run tests
      run: |
        python -m unittest discover -v

    - name: Run flake8 linting
      run: |
        flake8 *.py --max-line-length=120 --ignore=E302,E305

    - name: Run bandit security check
      run: |
        bandit -r *.py -f json

    - name: Run coverage
      run: |
        coverage run -m unittest discover
        coverage report
        coverage html

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
    - name: Send Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          Pipeline Статус: ${{ needs.test.result }}
          Репозиторий: ${{ github.repository }}
          Коммит: ${{ github.sha }}
          View logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}